version: '2.0'
services:
   php:
     container_name: portfolio_php
     build: .
     volumes:
     #for developpement purpose
     - ./src:/var/www/html
     ports:
       - "${APP_PORT}:80"
     restart: always
